# Fluent genomic data analysis with plyranges

## Instructor(s) name(s) and contact information

* Stuart Lee (lee.s@wehi.edu.au)
* Michael Lawrence (lawremi@gmail.com)

## Workshop Description

In this workshop, we will give an overview of how to perform low-level
analyses of genomic data using the  grammar of genomic data transformation
defined in the plyranges package. We will cover:

- introduction to GRanges
- overview of the core verbs for arithmetic, restriction, and aggregation of GRanges objects
- performing joins between GRanges objects
- designing pipelines to quickly explore data from AnnotationHub
- reading BAM and other file types as GRanges objects

The workshop will be a computer lab, in which the participants will be able to 
ask questions and interact with the instructors.

### Pre-requisites

This workshop is mostly self-contained however familiarity with the following would be useful:

- plyranges [vignette](https://sa-lee.github.io/plyranges/articles/an-introduction.html)
- the GenomicRanges and IRanges packages
- tidyverse approaches to data analysis

 
### Workshop Participation

Students will work through an Rmarkdown document while the instructors respond to any questions they have.

### _R_ / _Bioconductor_ packages used

- plyranges
- AnnotationHub
- GenomicRanges
- IRanges
- S4Vectors

### Time outline


| Activity                     | Time |
|------------------------------|------|
| Overview of GRanges          | 5m   |
| The plyranges grammar        | 20m  |
| I/O and data pipelines       | 20m  |

## Workshop goals and objectives

### Learning goals

* Understand that GRanges follows tidy data principles
* Apply the plyranges grammar to genomic data analysis

### Learning objectives

* Use AnnotationHub to find and summarise data
* Read files into R as GRanges objects
* Perform coverage analysis 
* Build data pipelines for analysis based on GRanges

# Workshop

## Introduction 

### What is plyranges?

The plyranges package is a domain specific language (DSL) built on top of the IRanges and
GenomicRanges packages.

### Why use plyranges?

### Who is this workshop for?

Let's get started!

### What are GRanges objects?

- modify figure and explanation from paper
- emphasise their tidyness
- why tidy is a useful cognitive tool

## The Grammar

Brief overview of the grammar (maybe include reference to table here at the bottom
of the document) including theory behind the join operations

### Worked example: exploring BigWig files from AnnotationHub

- this is a modified example from the paper, where we explore data from Human Epigenomics
Roadmap consortium, we take more time here to go through the core parts of the grammar

### Exercises 

Lead the workshop participant through computing the first example in 
(does not have to use the same data necessarily but is a good use case imo)
http://deeptools.readthedocs.io/en/latest/content/example_gallery.html#normalized-chip-seq-signals-and-peak-regions


## Data import and creating pipelines

Modified version of BAM example in paper (maybe using alpineData package)



